version: 2.1

orbs:
  python: circleci/python@0.2.1

publish_docker: &publish_docker
  docker:
    - image: circleci/buildpack-deps:stretch

  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build Docker image
        command: |
          docker build -t $IMAGE_NAME:$VERSION .
          echo "$DOCKER_PWD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push $IMAGE_NAME:$VERSION

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -c "import numpy; print(numpy.__version__)"
          name: Test

  build_publish_docker_latest:
    environment:
      IMAGE_NAME: aivanou/test
      VERSION: latest

    <<: *publish_docker

  build_publish_docker_version:
    environment:
      IMAGE_NAME: aivanou/test
      VERSION: 0.2.0rc0

    <<: *publish_docker


  verify_correct_version:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - run:
          name: Verify git tag and version consistency
          command: |
            python3 setup.py verify


  upload_to_pypi:

    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-cpu-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-cpu-dependencies-

      - run:
          name: Install python deps
          command: |
            sudo pip install twine

      - run:
          name: Setup .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PWD" >> ~/.pypirc
      - run:
          name: Build packages
          command: |
            python3 setup.py sdist bdist_wheel

      - run:
          name: Upload packages
          command: |
            python3 -m twine upload dist/*


workflows:
  main:
    jobs:
      - build-and-test
  circleci-docs-workflow:
    jobs:
      - verify_correct_version:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - build_publish_docker_version:
          requires:
            - verify_correct_version
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - build_publish_docker_latest:
          requires:
            - verify_correct_version
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - upload_to_pypi:
          requires:
            - verify_correct_version
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

