version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -c "import numpy; print(numpy.__version__)" 
          name: Test

  publish_docker:
    environment:
      IMAGE_NAME: aivanou/test
    docker:
      - image: circleci/buildpack-deps:stretch

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
            echo "$DOCKER_PWD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest


workflows:
  main:
    jobs:
      - build-and-test
      - publish_docker
